# Generated by Django 5.2.7 on 2025-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Bills', 'Bills'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
        ),
    ]
